# ==========================================================
# LANGCHAIN STUDY GUIDE: 03. STREAMING & BATCH
# ==========================================================

# --- STREAMING ---
# For long-running generations, waiting for the entire text can degrade user experience.
# Model streaming allows you to process and display tokens as soon as they are generated by the model.
# In LangChain, this is achieved using the `.stream()` method on the model instance.
# `.stream()` returns an iterator yielding chunks of the response.

# --- BATCHING ---
# If you have multiple independent inputs, executing them sequentially takes a long time.
# Model batching executes multiple inputs in parallel, optimizing performance and resource consumption.
# In LangChain, this is achieved using the `.batch()` method.

import os
from dotenv import load_dotenv
from langchain.chat_models import init_chat_model

load_dotenv()

def demonstrate_streaming(model):
    print("--- 1. STREAMING OUTPUT ---")
    query = "Write a short paragraph about the beauty of space exploration."
    
    # model.stream() returns an iterator of response chunks
    chunks = model.stream(query)
    
    # Iterate and print each chunk as it arrives
    for chunk in chunks:
        # We flush the buffer to ensure immediate print output
        print(chunk.content, end="", flush=True)
    print("\n")

def demonstrate_batch(model):
    print("--- 2. BATCH EXECUTION ---")
    queries = [
        "What is the capital of France?",
        "What is the capital of Japan?",
        "What is the capital of India?"
    ]
    
    # model.batch() runs queries concurrently
    responses = model.batch(queries)
    
    for query, response in zip(queries, responses):
        print(f"Q: {query} -> A: {response.content.strip()}")

if __name__ == "__main__":
    try:
        # Using a mock or a simple model initialization for demonstration
        model = init_chat_model("gpt-4o-mini", model_provider="openai")
        demonstrate_streaming(model)
        demonstrate_batch(model)
    except Exception as e:
        print("Model execution omitted or failed (check API keys):", e)

# ==========================================================
# REAL-LIFE USE CASES
# ==========================================================
# 1. LIVE CHAT SYSTEM: Stream responses chunk-by-chunk to the user interface (like ChatGPT web app)
#    so they see immediate progress instead of a blank screen.
# 2. BULK SENTIMENT ANALYSIS: Use batch processing to check the sentiment of 100 customer reviews
#    concurrently, reducing total execution time.

# ==========================================================
# MNC INTERVIEW QUESTIONS & ANSWERS
# ==========================================================
# Q1. What is the difference between `.invoke()`, `.stream()`, and `.batch()` in LangChain?
# A:  - `.invoke()`: Sends a single input and blocks until the full response is received.
#     - `.stream()`: Returns an iterator that streams chunks of the response in real-time.
#     - `.batch()`: Accepts a list of inputs and processes them concurrently under the hood.
#
# Q2. How does `.batch()` improve speed?
# A:  Instead of running requests synchronously (waiting for request 1, then request 2...),
#     `.batch()` leverages asyncio behind the scenes to trigger multiple concurrent HTTP connections
#     to the model provider, dramatically reducing overall latency for bulk operations.
