# ==========================================================
# LANGCHAIN STUDY GUIDE: 05. MESSAGES
# ==========================================================

# --- MESSAGES IN LANGCHAIN ---
# Messages are the fundamental unit of communication in LangChain's Chat Models.
# Instead of raw text strings, chat models expect a list of message objects.
# LangChain provides several core message classes in `langchain_core.messages`:
#
# 1. `SystemMessage`: Instruction to set the behavior/persona of the assistant.
# 2. `HumanMessage`: Input message sent by the user.
# 3. `AIMessage`: Response message generated by the model.
# 4. `ToolMessage`: Message containing the output of a tool execution, sent back to the model.

import os
from dotenv import load_dotenv
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from langchain.chat_models import init_chat_model

load_dotenv()

def demonstrate_messages(model):
    print("--- 1. CONSTRUCTING CONVERSATION CONTEXT ---")
    
    # We pass a list of message objects to preserve the conversation history/persona
    messages = [
        SystemMessage(content="You are a funny assistant who answers questions using pirate slang."),
        HumanMessage(content="What is the capital of India?"),
        # The LLM will respond with an AIMessage
    ]
    
    try:
        response = model.invoke(messages)
        print("Response object type:", type(response))
        print("AI Response content:", response.content)
        
        # Append the AI's response to keep the thread history
        messages.append(response)
        
        # Next follow-up question
        messages.append(HumanMessage(content="Tell me one famous monument there."))
        
        follow_up_response = model.invoke(messages)
        print("\nFollow-up Response:")
        print(follow_up_response.content)
        
    except Exception as e:
        print("Model invoke failed:", e)

if __name__ == "__main__":
    try:
        model = init_chat_model("gpt-4o-mini", model_provider="openai")
        demonstrate_messages(model)
    except Exception as e:
        print("Execution failed (check API keys):", e)

# ==========================================================
# REAL-LIFE USE CASES
# ==========================================================
# 1. CONVERSATIONAL CHATBOTS: Standard multi-turn chatbots store the message history as a list of
#    `HumanMessage` and `AIMessage` objects, appending new entries at each turn.
# 2. PROMPT INJECTION SHIELDING: Utilizing a strict `SystemMessage` to set system safety instructions
#    and guardrails that the user (`HumanMessage`) cannot easily override.

# ==========================================================
# MNC INTERVIEW QUESTIONS & ANSWERS
# ==========================================================
# Q1. Why does LangChain use message objects (like HumanMessage) instead of dictionaries?
# A:  Using typed classes ensures consistent schemas across different LLM backends (OpenAI, Anthropic, etc.).
#     It makes it easier to serialize/deserialize history and validates the structure before sending.
#
# Q2. What is the role of a `ToolMessage`?
# A:  When an LLM requests a tool call (via an AIMessage with `tool_calls` field), the system runs the tool
#     and returns the result inside a `ToolMessage`. The `ToolMessage` must include the matching `tool_call_id`
#     so the LLM knows which specific request this output belongs to.
