# ==========================================================
# FASTAPI STUDY GUIDE: 09. MIDDLEWARE & CORS
# ==========================================================

# --- WHAT IS MIDDLEWARE? ---
# A middleware is a function that runs BEFORE every request is processed by your route,
# and AFTER every response is generated by your route.
#
# Think of it like a security guard at the entrance of a building:
# 1. Inspects the visitor (the Request) as they enter (e.g., checks headers, logs arrival).
# 2. Lets the visitor go inside (runs the endpoint code).
# 3. Inspects the visitor (the Response) as they leave (e.g., adds security stamps/headers).

# --- WHAT IS CORS? ---
# CORS (Cross-Origin Resource Sharing) is a security mechanism enforced by web browsers.
# By default, a browser running a frontend app at `http://localhost:3000` is BLOCKED 
# from fetching data from a backend running at `http://localhost:8000`.
# To allow this, the backend must return specific CORS headers (like `Access-Control-Allow-Origin`)
# telling the browser: "Yes, I trust this frontend, let it read my data."

import time
import uvicorn
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(title="FastAPI: Middleware & CORS")

# ==========================================================
# 1. CONFIGURING CORS MIDDLEWARE
# ==========================================================
# List of origins (frontend URLs) that are allowed to make requests to our API.
# During development, we list localhost ports. For production, we list domain names.
origins = [
    "http://localhost:3000",      # React default port
    "http://localhost:5173",      # Vite/Vue default port
    "https://my-app.vercel.app",  # Production frontend URL
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,            # List of allowed origins
    allow_credentials=True,           # Allow cookies/session headers
    allow_methods=["*"],              # Allow all HTTP methods (GET, POST, PUT, DELETE, etc.)
    allow_headers=["*"],              # Allow all headers
)


# ==========================================================
# 2. WRITING A CUSTOM MIDDLEWARE
# ==========================================================
# We define a custom HTTP middleware that:
# 1. Starts a timer.
# 2. Passes the request to the endpoint.
# 3. Measures the time taken to complete.
# 4. Appends a custom header `X-Process-Time` to the response.
# 5. Prints request log to the terminal.
@app.middleware("http")
async def add_process_time_header(request: Request, call_next):
    # --- BEFORE REQUEST ---
    start_time = time.time()
    
    # Run the endpoint function and get the response
    # (call_next is a function that routes the request to its destination)
    response = await call_next(request)
    
    # --- AFTER REQUEST (BEFORE RESPONSE) ---
    process_time = time.time() - start_time
    
    # Add a custom header to the outgoing HTTP response
    response.headers["X-Process-Time"] = f"{process_time:.4f} seconds"
    
    # Print custom logs to terminal
    print(f"[Log] Request: {request.method} {request.url.path} | Time taken: {process_time:.4f}s")
    
    return response


# ==========================================================
# 3. DEMO ROUTE
# ==========================================================
@app.get("/")
async def root():
    return {"message": "Hello! Open your browser DevTools network tab to check response headers!"}

@app.get("/slow-endpoint")
async def slow():
    # Simulate a slow process
    time.sleep(0.5)
    return {"message": "Sorry to keep you waiting!"}


# ----------------------------------------------------------
# HOW TO RUN THIS FILE
# ----------------------------------------------------------
if __name__ == "__main__":
    uvicorn.run("09_middleware_cors:app", host="127.0.0.1", port=8000, reload=True)


# --- QUICK SUMMARY FOR RETESTING ---
# 1. Run this file: `python 09_middleware_cors.py`
# 2. Go to: http://127.0.0.1:8000/docs
# 3. Try executing the GET `/slow-endpoint` endpoint.
# 4. Check your Python terminal! You will see:
#    `[Log] Request: GET /slow-endpoint | Time taken: 0.5012s`
# 5. Open your web browser's developer tools (F12) -> Network tab, run the request, and click on it.
#    Look at the "Response Headers": you will find `x-process-time` listed there!


# ==========================================================
# REAL-LIFE USE CASES
# ==========================================================

# 1. CORS IN PRODUCTION (like any React + FastAPI app)
#    - Your React frontend runs at: https://myapp.vercel.app
#    - Your FastAPI backend runs at: https://api.myapp.com
#    - Without CORS config: Browser BLOCKS all API calls from frontend. App is broken.
#    - With CORSMiddleware(allow_origins=["https://myapp.vercel.app"]) → it works!
#    - This is the #1 setup error for new fullstack developers at MNCs.

# 2. REQUEST LOGGING MIDDLEWARE (like Datadog / CloudWatch in AWS)
#    - Every request is logged with: method, URL, status code, response time.
#    - In production, this log goes to a monitoring system like Datadog or ELK Stack.
#    - Engineers use these logs to debug: "Why did /checkout take 8 seconds at 11 PM?"

# 3. AUTHENTICATION MIDDLEWARE (like API Gateway at Infosys / TCS)
#    - A middleware checks the Authorization header on EVERY request before routing.
#    - If the token is missing → return 401 immediately without touching any route logic.
#    - This is more efficient than checking auth in every single route function.

# 4. RESPONSE COMPRESSION MIDDLEWARE
#    - GZip middleware compresses large JSON responses (like product lists with 1000 items).
#    - Reduces bandwidth by 70-80%, making mobile apps load much faster.
#    - Used by e-commerce backends to speed up product listing APIs.


# ==========================================================
# MNC INTERVIEW QUESTIONS & ANSWERS
# ==========================================================

# Q1. What is middleware in FastAPI and how is it different from a route?
# A:  A route handles ONE specific URL (e.g., GET /users).
#     Middleware wraps EVERY request/response, regardless of URL.
#     Middleware runs:
#       BEFORE: Can inspect/modify the incoming request (check headers, log, validate).
#       AFTER:  Can inspect/modify the outgoing response (add headers, compress, log time).
#     Think of it like airport security — EVERYONE goes through it before boarding.

# Q2. What is CORS and why does it exist?
# A:  CORS = Cross-Origin Resource Sharing.
#     Browsers enforce a "Same-Origin Policy" for SECURITY:
#       A page at https://evil.com CANNOT silently fetch data from https://yourbank.com.
#     CORS is the mechanism that lets servers say:
#       "I ALLOW requests from https://myapp.vercel.app". Browsers then permit it.
#     CORS is a BROWSER-only restriction. Tools like Postman/curl ignore it.
#     FastAPI's CORSMiddleware adds the correct headers for you automatically.

# Q3. What is the difference between allow_origins=["*"] and allow_origins=["https://myapp.com"]?
# A:  allow_origins=["*"] → ALLOWS ALL origins. Any website can call your API.
#       Use ONLY for: Fully public APIs (like open weather data APIs).
#       NEVER use for: APIs that handle user data, payments, or auth tokens!
#     allow_origins=["https://myapp.com"] → ONLY that specific frontend can call your API.
#       Correct approach for production. Much more secure.

# Q4. What is the `call_next` function inside a middleware?
# A:  `call_next(request)` is a function that passes the request to the NEXT handler
#     (either the next middleware or the actual route function).
#     The pattern is:
#       async def my_middleware(request, call_next):
#           # PRE-processing (runs BEFORE the route)
#           response = await call_next(request)   # ← route runs here
#           # POST-processing (runs AFTER the route)
#           return response
#     Without calling `call_next`, your middleware would intercept ALL requests and
#     none of your route functions would ever execute!

# Q5. How would you add an API key check to ALL routes using middleware?
# A:  @app.middleware("http")
#     async def api_key_middleware(request: Request, call_next):
#         api_key = request.headers.get("X-API-Key")
#         if not api_key or api_key != "my-secret-key":
#             return JSONResponse(status_code=401, content={"detail": "Invalid API Key"})
#         response = await call_next(request)  # Key is valid, proceed to route
#         return response
#     This protects EVERY route with one block of code. No Depends() needed on each route.
