// This file is auto-generated by scripts/generate_config.js
// Do not edit this file manually.

export interface TopicItem {
  title: string;
  slug: string;
  description: string;
  icon?: string;
  files: TopicFile[];
}

export interface TopicFile {
  title: string;
  slug: string;
  description?: string;
}

export const learningTopics: TopicItem[] = [
  {
    "title": "Python Learning",
    "slug": "python-learning",
    "description": "Python fundamentals, deep dives, and core concepts",
    "icon": "Python",
    "files": [
      {
        "title": "Python Strings And Methods (for Beginners)",
        "slug": "strings-and-methods"
      },
      {
        "title": "More On Strings: Multiline Strings (for Beginners)",
        "slug": "multiline-strings"
      },
      {
        "title": "Python User Input (for Beginners)",
        "slug": "user-input"
      },
      {
        "title": "Python Loops (for Beginners)",
        "slug": "loops"
      },
      {
        "title": "Python Type Hints (for Beginners)",
        "slug": "type-hints"
      },
      {
        "title": "Python Decorators (for Beginners)",
        "slug": "decorators"
      },
      {
        "title": "Python Async / Await (for Beginners)",
        "slug": "async-await"
      },
      {
        "title": "Python Exception Handling (for Beginners)",
        "slug": "exception-handling"
      },
      {
        "title": "Python Modules & Imports (for Beginners)",
        "slug": "modules-and-imports"
      },
      {
        "title": "Python Json Handling (for Beginners)",
        "slug": "json-handling"
      },
      {
        "title": "Python List Comprehensions (for Beginners)",
        "slug": "list-comprehensions"
      },
      {
        "title": "Python Lambda, Map, Filter (for Beginners)",
        "slug": "lambda-map-filter"
      },
      {
        "title": "Python Generators & Iterators (for Beginners)",
        "slug": "generators-and-iterators"
      },
      {
        "title": "Typeddict & Dataclasses (for Beginners)",
        "slug": "typeddict-and-dataclasses"
      },
      {
        "title": "Environment Variables (for Beginners)",
        "slug": "environment-variables"
      },
      {
        "title": "Python File Input / Output (file I/o) (for Beginners)",
        "slug": "file-io"
      },
      {
        "title": "Python Lists And Methods (for Beginners)",
        "slug": "lists-and-methods"
      },
      {
        "title": "Python Tuples And Methods (for Beginners)",
        "slug": "tuples-and-methods"
      },
      {
        "title": "Python Sets And Methods (for Beginners)",
        "slug": "sets-and-methods"
      },
      {
        "title": "Python Dictionaries (learning Guide)",
        "slug": "dictionaries-and-methods"
      },
      {
        "title": "Python If / Elif / Else (for Beginners)",
        "slug": "if-else"
      },
      {
        "title": "Python Matchcase / Switchcase (for Beginners)",
        "slug": "08b-match-case"
      },
      {
        "title": "Python Functions (for Beginners)",
        "slug": "functions"
      },
      {
        "title": "Python Classes & Oop (for Beginners)",
        "slug": "classes-and-oop"
      }
    ]
  },
  {
    "title": "FastAPI",
    "slug": "fastapi",
    "description": "FastAPI fundamentals and project structure",
    "icon": "FastAPI",
    "files": [
      {
        "title": "01. Introduction & Setup",
        "slug": "introduction-and-setup"
      },
      {
        "title": "02. Path Parameters",
        "slug": "path-parameters"
      },
      {
        "title": "03. Query Parameters",
        "slug": "query-parameters"
      },
      {
        "title": "04. Request Body & Pydantic",
        "slug": "request-body-pydantic"
      },
      {
        "title": "05. Response Models & Status Codes",
        "slug": "response-models-and-status"
      },
      {
        "title": "06. Error Handling",
        "slug": "error-handling"
      },
      {
        "title": "07. Dependency Injection (di)",
        "slug": "dependency-injection"
      },
      {
        "title": "08. Database Crud (sqlite & Orm)",
        "slug": "database-crud-sqlite"
      },
      {
        "title": "09. Middleware & Cors",
        "slug": "middleware-cors"
      },
      {
        "title": "10. Security & Jwt (json Web Tokens)",
        "slug": "security-jwt"
      },
      {
        "title": "11. File Uploads & Background Tasks",
        "slug": "background-tasks-and-files"
      }
    ]
  },
  {
    "title": "LangGraph",
    "slug": "langgraph",
    "description": "LangGraph agent workflows and graphs",
    "icon": "LangGraph",
    "files": []
  },
  {
    "title": "DSA in C++",
    "slug": "dsa-in-cpp",
    "description": "Data structures and algorithms in C++",
    "icon": "DSA",
    "files": []
  }
];

export function flattenTopicFiles(topics: TopicItem[]): (TopicFile & { topic: string })[] {
  const files: (TopicFile & { topic: string })[] = [];
  for (const topic of topics) {
    for (const file of topic.files) {
      files.push({ ...file, topic: topic.slug });
    }
  }
  return files;
}

export function getTopicBySlug(slug: string): TopicItem | undefined {
  return learningTopics.find((t) => t.slug === slug);
}

export const allTopicSlugs = learningTopics.map((t) => t.slug);
