// This file is auto-generated by scripts/generate_config.js
// Do not edit this file manually.

export interface TopicItem {
  title: string;
  slug: string;
  description: string;
  icon?: string;
  files: TopicFile[];
}

export interface TopicFile {
  title: string;
  slug: string;
  description?: string;
}

export const learningTopics: TopicItem[] = [
  {
    "title": "Python Learning",
    "slug": "python-learning",
    "description": "Python fundamentals, deep dives, and core concepts",
    "icon": "Python",
    "files": [
      {
        "title": "Day 1 First Program",
        "slug": "day-1-first-program"
      },
      {
        "title": "Strings And Methods",
        "slug": "strings-and-methods"
      },
      {
        "title": "Multiline Strings",
        "slug": "multiline-strings"
      },
      {
        "title": "Lists And List Methods",
        "slug": "lists-and-list-methods"
      },
      {
        "title": "Tuples",
        "slug": "tuples"
      },
      {
        "title": "Sets",
        "slug": "sets"
      },
      {
        "title": "Dictionaries",
        "slug": "dictionaries"
      },
      {
        "title": "User Input",
        "slug": "user-input"
      },
      {
        "title": "If Else Conditions",
        "slug": "if-else-conditions"
      },
      {
        "title": "Match Case",
        "slug": "match-case"
      },
      {
        "title": "Loops",
        "slug": "loops"
      },
      {
        "title": "Functions And Arguments",
        "slug": "functions-and-arguments"
      },
      {
        "title": "Type Hints",
        "slug": "type-hints"
      },
      {
        "title": "Oop Classes And Objects",
        "slug": "oop-classes-and-objects"
      },
      {
        "title": "Decorators",
        "slug": "decorators"
      },
      {
        "title": "Async Await",
        "slug": "async-await"
      },
      {
        "title": "Exception Handling",
        "slug": "exception-handling"
      },
      {
        "title": "Modules And Imports",
        "slug": "modules-and-imports"
      },
      {
        "title": "Json Handling",
        "slug": "json-handling"
      },
      {
        "title": "List Comprehensions",
        "slug": "list-comprehensions"
      },
      {
        "title": "Lambda Map Filter",
        "slug": "lambda-map-filter"
      },
      {
        "title": "Generators And Iterators",
        "slug": "generators-and-iterators"
      },
      {
        "title": "Typeddict And Dataclasses",
        "slug": "typeddict-and-dataclasses"
      },
      {
        "title": "Environment Variables",
        "slug": "environment-variables"
      },
      {
        "title": "File Io",
        "slug": "file-io"
      },
      {
        "title": "Dunder Methods",
        "slug": "dunder-methods"
      },
      {
        "title": "Context Managers",
        "slug": "context-managers"
      },
      {
        "title": "Decorators Deep Dive",
        "slug": "decorators-deep-dive"
      }
    ]
  },
  {
    "title": "FastAPI",
    "slug": "fastapi",
    "description": "FastAPI fundamentals and project structure",
    "icon": "FastAPI",
    "files": [
      {
        "title": "Introduction And Setup",
        "slug": "introduction-and-setup"
      },
      {
        "title": "Path Parameters",
        "slug": "path-parameters"
      },
      {
        "title": "Query Parameters",
        "slug": "query-parameters"
      },
      {
        "title": "Request Body Pydantic",
        "slug": "request-body-pydantic"
      },
      {
        "title": "Response Models And Status",
        "slug": "response-models-and-status"
      },
      {
        "title": "Error Handling",
        "slug": "error-handling"
      },
      {
        "title": "Dependency Injection",
        "slug": "dependency-injection"
      },
      {
        "title": "Database Crud Sqlite",
        "slug": "database-crud-sqlite"
      },
      {
        "title": "Middleware Cors",
        "slug": "middleware-cors"
      },
      {
        "title": "Security Jwt",
        "slug": "security-jwt"
      },
      {
        "title": "Background Tasks And Files",
        "slug": "background-tasks-and-files"
      },
      {
        "title": "Fastapi Overview",
        "slug": "fastapi-overview"
      }
    ]
  },
  {
    "title": "LangGraph",
    "slug": "langgraph",
    "description": "LangGraph agent workflows and graphs",
    "icon": "LangGraph",
    "files": []
  },
  {
    "title": "DSA in C++",
    "slug": "dsa-in-cpp",
    "description": "Data structures and algorithms in C++",
    "icon": "DSA",
    "files": []
  }
];

export function flattenTopicFiles(topics: TopicItem[]): (TopicFile & { topic: string })[] {
  const files: (TopicFile & { topic: string })[] = [];
  for (const topic of topics) {
    for (const file of topic.files) {
      files.push({ ...file, topic: topic.slug });
    }
  }
  return files;
}

export function getTopicBySlug(slug: string): TopicItem | undefined {
  return learningTopics.find((t) => t.slug === slug);
}

export const allTopicSlugs = learningTopics.map((t) => t.slug);
