const fs = require('fs');
const path = require('path');

const CONTENT_DIR = path.join(__dirname, '../src/content/learning');
const CONFIG_FILE = path.join(__dirname, '../src/config/learning.ts');

const STATIC_TOPICS = [
  {
    title: "Python Learning",
    slug: "python-learning",
    description: "Python fundamentals, deep dives, and core concepts",
    icon: "Python",
  },
  {
    title: "FastAPI",
    slug: "fastapi",
    description: "FastAPI fundamentals and project structure",
    icon: "FastAPI",
  },
  {
    title: "LangGraph",
    slug: "langgraph",
    description: "LangGraph agent workflows and graphs",
    icon: "LangGraph",
  },
  {
    title: "DSA in C++",
    slug: "dsa-in-cpp",
    description: "Data structures and algorithms in C++",
    icon: "DSA",
  }
];

const PREFERRED_ORDER = {
  "python-learning": [
    "day-1-first-program",
    "strings-and-methods",
    "multiline-strings",
    "lists-and-list-methods",
    "tuples",
    "sets",
    "dictionaries",
    "user-input",
    "if-else-conditions",
    "match-case",
    "loops",
    "functions-and-arguments",
    "type-hints",
    "oop-classes-and-objects",
    "decorators",
    "async-await",
    "exception-handling",
    "modules-and-imports",
    "json-handling",
    "list-comprehensions",
    "lambda-map-filter",
    "generators-and-iterators",
    "typeddict-and-dataclasses",
    "environment-variables",
    "file-io",
    "dunder-methods",
    "context-managers",
    "decorators-deep-dive"
  ],
  "fastapi": [
    "introduction-and-setup",
    "path-parameters",
    "query-parameters",
    "request-body-pydantic",
    "response-models-and-status",
    "error-handling",
    "dependency-injection",
    "database-crud-sqlite",
    "middleware-cors",
    "security-jwt",
    "background-tasks-and-files"
  ]
};

function extractTitle(filePath, slug) {
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    const lines = content.replace(/\r\n/g, '\n').split('\n');
    
    for (let line of lines) {
      line = line.trim();
      if (line === '') continue;
      
      if (line.startsWith('#')) {
        const clean = line.replace(/^#\s*/, '').replace(/[\-=\*#_]+/g, '').trim();
        
        if (clean.length > 2) {
          let title = clean.replace(/^\d+[\.\s_]*/, '');
          title = title.replace(/^FASTAPI STUDY GUIDE:\s*/i, '');
          title = title.replace(/^PYTHON STUDY GUIDE:\s*/i, '');
          
          return title.split(/\s+/)
            .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
            .join(' ');
        }
      } else if (line.startsWith('```')) {
        continue;
      } else {
        break;
      }
    }
  } catch (err) {
    console.error('Error extracting title from:', filePath, err);
  }
  
  return slug.split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

function generateConfig() {
  console.log('Scanning content directory...');
  const topics = [];

  for (const staticTopic of STATIC_TOPICS) {
    const topicDir = path.join(CONTENT_DIR, staticTopic.slug);
    const files = [];

    if (fs.existsSync(topicDir)) {
      const items = fs.readdirSync(topicDir);
      for (const item of items) {
        const fullPath = path.join(topicDir, item);
        const stat = fs.statSync(fullPath);
        
        if (stat.isFile() && (item.endsWith('.md') || item.endsWith('.py'))) {
          if (item.endsWith('-test.md') || item.endsWith('-test.py')) continue;

          const baseName = item.replace(/\.[^/.]+$/, "");
          const slug = baseName.replace(/^\d+[_ \-]/, "").replace(/_/g, "-");
          const title = extractTitle(fullPath, slug);
          
          files.push({
            title,
            slug,
            sortKey: item.toLowerCase()
          });
        }
      }
    }

    // Sort files by preferred order first, then alphabetically
    files.sort((a, b) => {
      const orderList = PREFERRED_ORDER[staticTopic.slug] || [];
      const indexA = orderList.indexOf(a.slug);
      const indexB = orderList.indexOf(b.slug);
      
      if (indexA !== -1 && indexB !== -1) {
        return indexA - indexB;
      }
      if (indexA !== -1) return -1;
      if (indexB !== -1) return 1;
      
      return a.sortKey.localeCompare(b.sortKey);
    });

    const cleanFiles = files.map(({ title, slug }) => ({ title, slug }));

    topics.push({
      ...staticTopic,
      files: cleanFiles
    });
  }

  const code = `// This file is auto-generated by scripts/generate_config.js
// Do not edit this file manually.

export interface TopicItem {
  title: string;
  slug: string;
  description: string;
  icon?: string;
  files: TopicFile[];
}

export interface TopicFile {
  title: string;
  slug: string;
  description?: string;
}

export const learningTopics: TopicItem[] = ${JSON.stringify(topics, null, 2)};

export function flattenTopicFiles(topics: TopicItem[]): (TopicFile & { topic: string })[] {
  const files: (TopicFile & { topic: string })[] = [];
  for (const topic of topics) {
    for (const file of topic.files) {
      files.push({ ...file, topic: topic.slug });
    }
  }
  return files;
}

export function getTopicBySlug(slug: string): TopicItem | undefined {
  return learningTopics.find((t) => t.slug === slug);
}

export const allTopicSlugs = learningTopics.map((t) => t.slug);
`;

  fs.writeFileSync(CONFIG_FILE, code, 'utf-8');
  console.log(`Successfully generated config file at ${CONFIG_FILE}`);
}

generateConfig();
